version: 0.0
os: linux
files:
  - source: /
    destination: /var/www/html
    overwrite: false
hooks:
  BeforeInstall:
    - location: scripts/install_dependencies.sh
      timeout: 300
      runas: root
  AfterInstall:
    - location: scripts/install_composer_dependencies.sh
      timeout: 300
      runas: root
      
